name: Data model and Documentation refresh
run-name: DBT Run triggered by @${{ github.actor }}
on: workflow_dispatch
jobs:
  build-docs:
    name: DBT docs
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-labs/dbt-snowflake:1.9.latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: dbt deps
      - run: python -m pip install elementary-data
      - run: python -m pip install 'elementary-data[snowflake]'
      - run: dbt docs generate --target dev
        env:
          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
      - run: dbt test
        env:
          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
      - run: edr --help
      - run: edr report --profiles-dir ./profiles.yml
        env:
          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
      - run: sed -i 's|Docs|DBT Docs|g' elementary_report.html
      - run: sed -i 's|https://docs.elementary-data.com/introduction|./index.html|g'
      - run: |
          mkdir docs
          cp target/index.html docs
          cp target/manifest.json docs
          cp target/catalog.json docs
          cp edr_target/elementary_outpus.json docs
          cp edr_target/elementary_report.html docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/
  deploy-pages:
    name: Deploy Github Pages
    needs: build-docs
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.build-docs.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
