version: 1

sources:
  - name: source_db
    description: "Snowflake database with ingested SAP tables."
    database: SSI_SAP_TO_SNOW_CLONESSI
    schema: RAW
    tables:
      - name: eket
        description: "source for POSschedule"
      - name: tcurx
        description: "Decimal Places in Currencies"
      - name: kna1
        description: "General Data in Customer Master"
      - name: adrc
        description: "Addresses (Business Address Services)"
      - name: t005
        description: "Countries"
      - name: t005t
        description: "Country Names"
      - name: tspa
        description: "Organizational Unit: Sales Divisions"
      - name: tspat
        description: "Organizational Unit: Sales Divisions: Texts"
      - name: tvtw
        description: "Organizational Unit: Distribution Channels"
      - name: tvtwt
        description: "Organizational Unit: Distribution Channels: Texts"
      - name: tvko
        description: "Organizational Unit: Sales Organizations"
      - name: tvkot
        description: "Organizational Unit: Sales Organizations: Texts"
      - name: t001
        description: "Company Codes"
      - name: tvlst
        description: "Deliveries: Blocking Reasons/Scope: Texts"
      - name: tvfst
        description: "Billing : Blocking Reason Texts"
      - name: mara
        description: "General Material Data"
      - name: makt
        description: "Material Descriptions"
      - name: prcd_elements
        description: "Pricing Elements"
      - name: vbrk
        description: "Billing Document: Header Data"
      - name: vbrp
        description: "Billing Document: Item Data"
      - name: lips
        description: "SD document: Delivery: Item data"
      - name: likp
        description: "SD Document: Delivery Header Data"
      - name: vbap
        description: "Sales Document: Item Data"
      - name: vbep
        description: "Sales Document: Schedule Line Data"
      - name: vbpa
        description: "Sales Document: Partner"
      - name: vbak
        description: "Sales Document: Header Data"
      - name: vbuk
        description: "Sales Document: Header Status and Administrative Data"
      - name: konv
        description: "Conditions for the Billing Documents (Transaction Data)"
      - name: t002
        description: "source for VendorPerformance"
      - name: tcurr
        description: "source for VendorPerformance"
      - name: ekko
        description: "source for VendorPerformance"
      - name: ekpo
        description: "source for VendorPerformance"
      - name: ekbe
        description: "source for VendorPerformance"
      - name: t009
        description: "source for VendorPerformance"
      - name: t009b
        description: "source for VendorPerformance"
      - name: t024e
        description: "source for VendorPerformance"
      - name: t024
        description: "source for VendorPerformance"
      - name: lfa1
        description: "source for VendorPerformance"
      - name: t134
        description: "source for VendorPerformance"
      - name: t134t
        description: "source for VendorPerformance"

  #- name: source_db2
   # description: "Snowflake database."
    #database: SSI_SAP_TO_SNOW
    #schema: REPORT
    #tables:
     # - name: calendar_date_dim
      #  description: "source for POSschedule"
      #- name: deliveries
      #  description: "source for DeliveriesStatus_PerSalesOrg"
      #- name: SalesOrganizationsMD
       # description: "source for DeliveriesStatus_PerSalesOrg"
      #- name: MaterialsMD
       # description: "source for VendorPerformance"

models:
  - name: ordertocash
    description: "Data relating to the sales and delivery process, including information on the quantity delivered, net price, delivery and billing dates, and overall delivery status. It also includes details on the customer, material, and billing information."
    columns:
      - name: client_mandt
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: SalesDocument_VBELN
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: Item_POSNR
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: CustomerNumber
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: MaterialNumber
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
  - name: ordertocash_v2
    description: "Data relating to the sales and delivery process, including information on the quantity delivered, net price, delivery and billing dates, and overall delivery status. It also includes details on the customer, material, and billing information."
    columns:
      - name: client_mandt
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: SalesDocument_VBELN
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: Item_POSNR
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: CustomerNumber
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: MaterialNumber
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
  - name: calendar_date_dim
    description: "Dates and their corresponding calendar attributes."